packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - esbuild
  - prisma
